# Docker Compose configuration for consolidated match-list-processor service
#
# Architecture: Single unified service with integrated change detection
# - No webhook dependencies (removed in Phase 1B)
# - Enhanced change categorization system
# - Simplified deployment with external service dependencies
#
# Updated: 2025-08-31 - Phase 1B configuration consolidation
services:
  process-matches-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Stockholm
      # Unified processor configuration
      - PROCESSOR_MODE=unified
      - RUN_MODE=service
      # Enhanced change categorization settings
      - ENABLE_CHANGE_CATEGORIZATION=true
      - CHANGE_PRIORITY_SAME_DAY=critical
      # Data storage configuration
      - DATA_FOLDER=/data
      - PREVIOUS_MATCHES_FILE=previous_matches.json
      # Service URLs
      - FOGIS_API_CLIENT_URL=http://fogis-api-client-service:8080
      - WHATSAPP_AVATAR_SERVICE_URL=http://whatsapp-avatar-service:5002
      - GOOGLE_DRIVE_SERVICE_URL=http://google-drive-service:5000
      - PHONEBOOK_SYNC_SERVICE_URL=http://fogis-calendar-phonebook-sync:5003
      # Processing settings
      - MIN_REFEREES_FOR_WHATSAPP=2
      - TEMP_FILE_DIRECTORY=/tmp
      # Google Drive settings
      - GDRIVE_FOLDER_BASE=WhatsApp_Group_Assets
      # Logging configuration
      - LOG_LEVEL=INFO
      - LOG_FORMAT=%(asctime)s - %(levelname)s - %(message)s
    container_name: process-matches-service
    networks:
      - fogis-network
    volumes:
      - process-matches-data:/data
      - .:/app
    ports:
      - "8000:8000"  # Health check endpoint
    restart: unless-stopped
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/simple"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Change from condition-based dependencies to simple dependencies
    depends_on:
      - whatsapp-avatar-service
      - google-drive-service
      - fogis-api-client-service
      - fogis-sync
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app

  whatsapp-avatar-service:
    extends:
      file: ../TeamLogoCombiner/docker-compose.yml
      service: whatsapp-avatar-service
    networks:
      - fogis-network
    volumes:
      - ../TeamLogoCombiner/assets:/app/assets:ro
    ports:
      - "5002:5002"
    # Keep healthcheck commented out as /health endpoint is not implemented
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s

  google-drive-service:
    extends:
      file: ../google-drive-service/docker-compose.yml
      service: google-drive-service
    networks:
      - fogis-network
    volumes:
      - google-drive-service-data:/app
    ports:
      - "5001:5000"  # Changed host port to 5001
    # Keep healthcheck commented out as /health endpoint is not implemented
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s

  fogis-api-client-service:
    extends:
      file: ../fogis_api_client_python/docker-compose.yml
      service: fogis-api-client
    networks:
      - fogis-network
    volumes:
      - ../fogis_api_client_python/data:/app/data
      - ../fogis_api_client_python/logs:/app/logs
    ports:
      - "8080:8080"
    # Enable healthcheck as /hello endpoint is working
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fogis-sync:
    extends:
      file: ../FogisCalendarPhoneBookSync/docker-compose.yml
      service: fogis-sync
    image: fogiscalendarphonebooksync-fogis-sync:v1.0.1  # Added version tag
    build:
      context: ../FogisCalendarPhoneBookSync
      no_cache: true  # Force rebuild
    networks:
      - fogis-network
    volumes:
      - ../FogisCalendarPhoneBookSync/token.json:/app/token.json
      - ../FogisCalendarPhoneBookSync/data:/app/data
    ports:
      - "5003:5003"
    # Enable healthcheck as /health endpoint is working
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  fogis-network:
    external: true

volumes:
  process-matches-data:
    external: true
  google-drive-service-data:
    external: true
